# Generated by Django 5.2.1 on 2025-06-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_teachers_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachers',
            name='slug',
            field=models.SlugField(auto_created=True, max_length=200, unique=True),
        ),
    ]
